### ISSUE TITLE
Mixpanel network requests occurring with tracking disabled

### ISSUE THREAD

**Issue by grahamwetzler** [Montreal-Analytics/dbt-gloss#127]
**Describe the bug**
With tracking disabled per the README, Mixpanel network requests are still occurring and failing due to Zscaler use in our org.

```
Mixpanel Error: HTTPSConnectionPool(host='api.mixpanel.com', port=443): Max retries exceeded with url: /track (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))
```

**To Reproduce**
1. `.dbt-checkpoint.yaml`:
```
version: 1
disable-tracking: true
```
2. Run pre-commit, i.e. `pre-commit run check-model-has-description --all-files`

**Expected behavior**
With tracking disabled, no Mixpanel network requests should occur.

**Version:**
v1.1.0

**Additional context**

**Comment by PeteCorbettWS** [comment]
@grahamwetzler 
Below worked for me
pinning to [latest commit to main](a055f90be64d81e48d180f968529b0e2ae271926) and ensuring config file matches completely to expected default i.e. .dbt-checkpoint.yaml NOT .dbt-checkpoint.yml
OR
alternatively set the config file name as '.dbt-gloss.yaml' until the next release

**Comment by grahamwetzler** [comment]
Using `a055f90` instead of `v1.1.0` worked for me, thanks @PeteCorbettWS.
