### ISSUE TITLE
Ignore all Disabled models for checks

### ISSUE THREAD

**Issue by culpgrant** [Montreal-Analytics/dbt-gloss#129]
**Describe the feature you'd like**
If a model is disabled (enabled=false) then ignore those models for the checks.

**Additional context**

**Comment by eugenekim-orrum** [comment]
Ran into this today in a dev build where I wanted to disable some models until upcoming changes to source were actually made. I'll stop being lazy and put those disabled models on a separate branch, but it would be nice!
