### ISSUE TITLE
check-model-has-all-columns doesn't work with ephemeral models

### ISSUE THREAD

**Issue by VDFaller** [Montreal-Analytics/dbt-gloss#146]
**Describe the bug**
when I run any model that's ephemeral materialization.   This check fails.  Ephemeral models apparently don't make it into the catalog? 

**To Reproduce**
1. make ephemeral model
2. add table/columns to properties.yml
3. dbt docs generate
4. commit
5. fail

**Expected behavior**
I would expect it to pass because the columns ARE in my properties file

**Version:**
dbt-checkpoint v1.0.0 
dbt-databricks==1.5.5
pre-commit==3.3.3

**Additional context**
If the "Ephemeral models don't make it into the catalog" thing is true, I expect this to affect more than just this one test.

**Comment by ssassi** [comment]
Possible solutions:
1. to provide the production's db catalog.json, so dbt-checkpoint looks on that file when the table was not found on the current db's catalog.json.
2. Add an argument that will make dbt-checkpoint skip deferred models on this hook

**Comment by nathangriffiths-cdx** [comment]
dbt-checkpoint should probably ignore ephemeral models since they don't exist in the database (and therefore the catalog) so there is no way for dbt-checkpoint to compare the output columns to the columns defined in yml. 
This is similar to why dbt model contracts are not supported for ephemeral models either.

**Comment by noel** [comment]
Have you tried this with the latest version?It should already ignore ephemeral models

**Comment by nathangriffiths-cdx** [comment]
> Have you tried this with the latest version?It should already ignore ephemeral models
@noel I don't have ephemeral models, so maybe @VDFaller can confirm this.

**Comment by VDFaller** [comment]
@noel seems like you're right.  upgraded to 1.1.1 and now no ephemeral models fail.  Sorry for the delay

**Comment by noel** [comment]
great.
