### ISSUE TITLE
create `check-model-has-contract` & `check-model-has-constraints`

### ISSUE THREAD

**Issue by cl-fl** [Montreal-Analytics/dbt-gloss#154]
**Describe the feature you'd like**
With the addition of [model contracts](https://docs.getdbt.com/reference/resource-configs/contract) and [constraints](https://docs.getdbt.com/reference/resource-properties/constraints) as part of 1.5, it would be great to have a hook to check that a model contract has been enforced and another one to check the model has a number of constraints (similar to the `check-model-has-tests` hook).

**Additional context**
This would be very useful to enforce model governance. More details also available in [contracts GH thread](https://github.com/dbt-labs/dbt-core/discussions/6726)

**Comment by xasm83** [comment]
added PR https://github.com/dbt-checkpoint/dbt-checkpoint/pull/218

**Comment by cl-fl** [comment]
Solved with https://github.com/dbt-checkpoint/dbt-checkpoint/pull/218, thank you!
