### ISSUE TITLE
dbt-debug pre-hook

### ISSUE THREAD

**Issue by herbertstos** [Montreal-Analytics/dbt-gloss#157]
Describe the feature you'd like
In our DBT project we use the dbt debug feature to show the connection in ci/cd, we would like to request this pre-hook to show the connection in the deploy log to facilitate future debugging.

**Comment by BAntonellini** [comment]
Hey @herbertstos, we are not planning to cover more dbt commands as pre-commit hooks than there are already available. When we need to do these actions, we typically do it as another step in the CI script. Long term we want to keep checkpoint focused on hooks, not on dbt command running as those can be handled in other ways.
