### ISSUE TITLE
temporarily disabled on pre-commit.com/hooks -- hook name too long

### ISSUE THREAD

**Issue by asottile** [Montreal-Analytics/dbt-gloss#164]
hello hello!  thanks for writing an integration for pre-commit.  we've recently added a more strict requirement for hooks on the [hooks page](https://pre-commit.com/hooks) where hook `name`s must be <= 50 characters otherwise they will cause wrapping by default in pre-commit

please update your hook names to be within this requirement and then re-enable your repository (by uncommenting it) -- for more details check out https://github.com/pre-commit/pre-commit.com/pull/901

thanks!

**Comment by pgoslatara** [comment]
Addressed by [#954](https://github.com/pre-commit/pre-commit.com/pull/954).

@BAntonellini Can you close this issue?

**Comment by BAntonellini** [comment]
Fixed in #209
