### ISSUE TITLE
create check-exposure-has-meta-keys

### ISSUE THREAD

**Issue by damiantl** [Montreal-Analytics/dbt-gloss#174]
**Describe the feature you'd like**
With the addition of exposures, apart from models and sources, it would be great to have a hook to check if they have meta keys defined or not. Like for example the **check-model-has-meta-keys** or **check-source-has-meta-keys** we already have.

Similar to what we have for models with the "--allow-extra-keys" flag, might be also very intersting to have for exposures.

**Additional context**
This would be really useful to enforce exposure governance.

**Comment by BAntonellini** [comment]
Released in [v1.2.1](https://github.com/dbt-checkpoint/dbt-checkpoint/releases/tag/v1.2.1)
