### ISSUE TITLE
Support for multiple data types for check-column-name-contract hook

### ISSUE THREAD

**Issue by coldborecapital** [Montreal-Analytics/dbt-gloss#178]
We use the suffix _at for any type of date, timestamp, or timestamp_tz column. I've tried a few different approaches, but it doesn't look like there is a way to specify multiple data types under the `--dtype` arg. If this is possible and I just don't have the right syntax, then I would like to change my request to ask that the docs be updated to show this. 

Example of what I would like (or any similar variation).

```
      - id: check-column-name-contract
        name: Check Column Name Contract Boolean
        args: [ "--pattern", ".*_at", "--dtype", "(timestamp|timestamp_tz|date)" ]
```

**Comment by BAntonellini** [comment]
Implemented in #180
