### ISSUE TITLE
Typo in docs for how to use --exclude

### ISSUE THREAD

**Issue by lindsay-secoda** [Montreal-Analytics/dbt-gloss#185]
The docs say this:
Hooks that use --exclude in their args, should receive it this way:

```
- id: check-model-has-tests
  description: "Ensures that the model has a number of tests"
  args: ["--test-cnt", "1", "--exclude models/demo", "--"]
```

This doesn't work for hooks like  `check-model-has-all-columns`. But this does:
```
 - id: check-model-has-all-columns # Ensures that mart models have all columns in the database also specified in the .yml
      args: [--exclude, "models/marts", "--"]
```

**Comment by rwagner-branch** [comment]
I'm also struggling to get the exclude flag to work as intended. Just confirming, it works for you if you do _not_ put `--exclude` in quotes (but you do quote all the file/folder references?)

**Comment by BAntonellini** [comment]
Hi @lindsay-secoda and @rwagner-branch, you're right.

`--exclude` and `pattern` are two separate string entries on `args`. This way, the argument parser can handle the pattern correctly.

Fixing docs right away
