### ISSUE TITLE
check_source_has_all_columns reports failure due to use of lower()

### ISSUE THREAD

**Issue by StuartMiddleton** [Montreal-Analytics/dbt-gloss#192]
**Describe the bug**
Hook returns failure when comparing upper-case field names to the catalogue, even when the dbt project refers to fields in all upper case.

This is no-doubt due to the use of lower() on line 22, with no corresponding use of lower() elsewhere.

**To Reproduce**
1. Create a simple model with upper-case field names.
2. Execute dbt run.
3. Execute check_source_has_all_columns pre-commit hook.
4. Returns failure similar to following:

source1.table1: columns in SOURCE but not in db (catalog.json):
- name: FIELD1
- name: FIELD2
- name: FIELD3
source1.table1: columns in db (catalog.json) but not in SOURCE:
- name: field1
- name: field2
- name: field3

**Expected behavior**
Pass test when field names (and cases) match in both catalog.json and source table.

**Version:**
v0.1.0

**Additional context**

**Comment by BAntonellini** [comment]
Fixed in #197
