### ISSUE TITLE
dbt-docs-generate speedup possibility with --no-compile?

### ISSUE THREAD

**Issue by awal11** [Montreal-Analytics/dbt-gloss#205]
The generation of catalog.json seems to be the slowest part of the whole checkpoints evaluation process.

But I noticed that if do `dbt-parse` and then `dbt docs generate` with additional parameter `--no-compile` it's way faster.

Would it make sense to update https://github.com/dbt-checkpoint/dbt-checkpoint/blob/main/README.md#setup to show this as default setup?

I am happy to provide a patch, just need to understand the preferred approach.

**Comment by pgoslatara** [comment]
@awal11 I don't think this is a bug, but happy to explore the issue at play.

`dbt-parse` is a new hook, in fact it hasn't been included in a release yet, so I'm interested in hearing your experience of using it. Can you provide some number surrounding your "way faster" comment? Also helpful would be the number of dbt sources/modes you have and the number of threads you use.

I run the `dbt-docs-generate` hook with 64 threads [here](https://github.com/pgoslatara/dbt-beyond-the-basics/blob/stg/.pre-commit-config.yaml#L59), that may be another approach to speed up this hook.

**Comment by awal11** [comment]
@pgoslatara thank you for the response. Clearly this is not a bug, but also not a 'new feature', so I did not know how to categorize it.

Locally I am working on a lowly 2018 Intel Core i5-8350U with 4 cores and 8 threads.
My database is Snowflake with  562 tests, 1 operation, 14 models, 48 sources.
I have my dbt config set to 16 threads and moving to 64 threads did not change anything significant.

I ran some more tests (in no scientific manner)  repeated each of them ~5 times and show the median below:

|  clean state: dbt-parse + dbt-docs-generate (with --no-compile) |  clean state: dbt-docs-generate (this compiles code by default, so no need to do parse or compile) | with existing target folder:  dbt-parse + dbt-docs-generate (with --no-compile)  | with existing target folder:  dbt-docs-generate|
| - | - | - | - |
| 32 sec | 45 sec | 24 sec | 36 sec |

The 3 and 4 column probably benefit from the partial_parse.
My conclusion is that it is indeed as expected a bit faster, so could be documented for others.

**Comment by pgoslatara** [comment]
@awal11 Thanks for the numbers, they are informative of what you are saying. I agree with your original proposal, it would be nice to update the `README` with a note that mentions the `--no-compile` arg. Are you open to creating a PR for this?

**Comment by astro30** [comment]
Hey @awal11 @pgoslatara, looks like we are facing the same problem -> performance
My approach is to run the `dbt docs generate` on only staged models.
Here is my raised issue here [https://github.com/dbt-checkpoint/dbt-checkpoint/issues/205](https://github.com/dbt-checkpoint/dbt-checkpoint/issues/205). I am working on it in my fork

**Comment by BAntonellini** [comment]
Hi @astro30 , isn't #196 the one you mention?

**Comment by astro30** [comment]
Oopsie, that's exact, my bad !

**Comment by awal11** [comment]
Added pull request: https://github.com/dbt-checkpoint/dbt-checkpoint/pull/211

The updates for dbt-generate-docs description in Hooks.md are provided already by @astro30 in https://github.com/dbt-checkpoint/dbt-checkpoint/pull/210

@BAntonellini @pgoslatara - please bear in mind that now all the examples in Readme.md that refer to release 1.2.1 and use `dbt-parse` are invalid as `dbt-parse` was not included in that release. 
Once the release is published - the documents should be amended. I could do it, just tell me how the upcoming release will be named.

**Comment by BAntonellini** [comment]
Hey guys, we've accepted the proposed `cmd-flags --no-compile` readme changes.

Also, FYI, we're planning to release `v2.0.0` later today, bumping Major version as many changes (specially @pgoslatara's `dbt parse`) are breaking ones, requiring users to have `dbt-core >= 1.5`.

@awal11 should we close this?

**Comment by awal11** [comment]
Yes, perfect, thank you!
Would be great to have this one addressed as well https://github.com/dbt-checkpoint/dbt-checkpoint/issues/203 but I assume it's a bit more complicated.
