### ISSUE TITLE
New Release - check-model-has-contract

### ISSUE THREAD

**Issue by paramjitsingh006** [Montreal-Analytics/dbt-gloss#230]
**Describe the bug**
I can see changes related to `check-model-has-contract` made in early may and hence they are not part of the latest release `v2.0.1`. Any plans to create a new release so these changes can be included. In absence, branch name `main` needs to be used in pre-commit (which is not the recommended approach)

**To Reproduce**
1. ...
2. ...
+ include sql script and/or dbt schema files.

**Expected behavior**
`check-model-has-contract` should be available as part of new release `v2.0.2`

**Version:**
v2.0.1

**Additional context**

**Comment by BAntonellini** [comment]
@paramjitsingh006 you are right.

We are planning on releasing `v2.0.2` this week. We are waiting for anything else that could be added.

For the time being, I agree pointing to `main` isn't a good practice, though you can point to `56ca5a1` or any specific commit.
