### ISSUE TITLE
Possibility to change the dbt root for all hooks

### ISSUE THREAD

**Issue by sdebruyn** [Montreal-Analytics/dbt-gloss#39]
I work in a monorepo and dbt is not at the root of the repo. A lot of checks fail because of this and have to be adapted with the args, but it's not possible for all of them. E.g. the dbt deps hooks does not allow you to change where it is executed. Maybe there is an easier way to apply this and allow the feature for all the hooks.

**Comment by misteliy** [comment]
This is very relevant for us as well!

**Comment by joaobernardopa** [comment]
I just opened a MR that tries to address this issue by implementing a new optional argument for dbt-commands. It allows specifying a relative path to the root of the dbt project, thus enabling monorepos to leverage all pre-commit-dbt hooks. Please @tomsej kindly take a look and let me know your thoughts.

**Comment by samLozier** [comment]
I would also benefit greatly from this change.

**Comment by BAntonellini** [comment]
Solved in #138
