### ISSUE TITLE
Jinja comments cause check-script-has-no-table-name to hang

### ISSUE THREAD

**Issue by katieclaiborne** [Montreal-Analytics/dbt-gloss#64]
**Describe the bug**
Changes to dbt models containing Jinja comments `{# #}` cause the `check-script-has-no-table-name` hook to hang.

**To Reproduce**
1. Add a Jinja comment `{# #}` to a dbt model
2. Run the `check-script-has-no-table-name` hook
```
-- my_model.sql
{# adding this comment will cause the hook to hang #}
```
**Expected behavior**
I expected the hook to run normally, completing within a few seconds.

**Version:**
v0.1.0

**Additional context**
We noticed this issue when our GitHub action began to time out on certain pull requests, and confirmed that replacing Jinja comment syntax `{# #}` with `--` resolved it. The problem seems similar to #46, but I don't know regex well enough to pinpoint the change needed.

**Comment by crtjer** [comment]
We also have this in our github actions failing. It would be nice to keep the jinja comments if possible.

**Comment by kiliantscherny** [comment]
We've also just had the same problem in our GH actions workflow, seemingly also caused by Jinja comment syntax. Hadn't had this issue in the past,  @katieclaiborne @crtjer did you eventually resolve it without reverting to regular SQL comments (`--`)? We're on v3.1.1

**Comment by katieclaiborne** [comment]
Hmm, we're not seeing the issue anymore, but I don't actually know where a fix might have occurred.

Have you tried using the new [v1.1.0](https://github.com/dbt-checkpoint/dbt-checkpoint/releases/tag/v1.1.0)?

**Comment by JFrackson** [comment]
I can confirm that as described in the original message from @katieclaiborne  this is no longer an issue when using v1.1.0. I don't have a link to a specific PR, unfortunately but my test now shows this as resolved. 

As for the GH action, we've published a new one [here](https://github.com/marketplace/actions/dbt-checkpoint) and are working out a few remaining hiccups with it now.

I'm closing this issue as the original has been resolved, but please open a new issue if there is a specific problem with the Github Action to help us resolve that! CC @crtjer @kiliantscherny

**Comment by kiliantscherny** [comment]
Awesome, thank you both, I can also confirm that updating dbt-checkpoint to v1.1.0 fixed our issues too 🙌
