### ISSUE TITLE
Feature request: Create a hook dbt-seed

### ISSUE THREAD

**Issue by FrankTub** [Montreal-Analytics/dbt-gloss#79]
**dbt-seed hook**
In my ci run I would like to be able to run the dbt seed command from `pre-commit-dbt`. AFAIK this is currently not possible.

**Comment by BAntonellini** [comment]
Hey @FrankTub, we are not planning to cover more dbt commands as pre-commit hooks than there are already available. When we need to do these actions, we typically do it as another step in the CI script. Long term we want to keep checkpoint focused on hooks, not on dbt command running as those can be handled in other ways.
