### ISSUE TITLE
`check_macro_arguments_have_desc` hook fails to parse arguments

### ISSUE THREAD

**Issue by hacherix** [Montreal-Analytics/dbt-gloss#86]
**Describe the bug**

`check_macro_arguments_have_desc` hook raises the following error even though the content of the files is ok.
Other hooks are working correctly, including `check_macro_has_description`.

```
Traceback (most recent call last):
  File "/home/mache/.cache/pre-commit/repo0ldja9vt/py_env-python3/bin/check-macro-arguments-have-desc", line 8, in <module>
    sys.exit(main())
  File "/home/mache/.cache/pre-commit/repo0ldja9vt/py_env-python3/lib/python3.10/site-packages/pre_commit_dbt/check_macro_arguments_have_desc.py", line 90, in main
    status_code, _ = check_argument_desc(paths=args.filenames, manifest=manifest)
  File "/home/mache/.cache/pre-commit/repo0ldja9vt/py_env-python3/lib/python3.10/site-packages/pre_commit_dbt/check_macro_arguments_have_desc.py", line 52, in check_argument_desc
    for key, value in item.macro.get("arguments", {}).items()
AttributeError: 'list' object has no attribute 'items'
```

**To Reproduce**

Steps to reproduce the behavior using getdbt examples:

1. `macros/schema.yml`
```
version: 2

macros:
  - name: cents_to_dollars
    description: A macro to convert cents to dollars
    arguments:
      - name: column_name
        type: string
        description: The name of the column you want to convert
      - name: precision
        type: integer
        description: Number of decimal places. Defaults to 2.
```

2. `macros/cents_to_dollars.sql`
```
{% macro cents_to_dollars(column_name, precision=3) %}
    COALESCE (TRUNC(CAST({{ column_name }}/100 AS numeric), {{ precision }}), 0)
{% endmacro %}
```

3. Execute the following command after `dbt deps`, `dbt compile` and `dbt docs generate`:
`pre-commit run check-macro-arguments-have-desc --files macros/cents_to_dollars.sql`

**Expected behavior**
The hook should pass successfully.

**Version:**
commit 34a2341234675d7a6b61766b2c33bdd5c33d090b (current latest commit)

**Additional context**
It looks like the problem is here: `for key, value in item.macro.get("arguments", {}).items()`
The hook is guessing the arguments key contains a dictionary while this is a list of dictionaries.
https://github.com/offbi/pre-commit-dbt/blob/main/pre_commit_dbt/check_macro_arguments_have_desc.py#L52

**Comment by fontclos** [comment]
We are hitting this issue as well. Any chance this gets fixed?

**Comment by BAntonellini** [comment]
Hey @fontclos, thanks for bringing out your case.

Indeed, there was a bug in Macro arguments. We'll release a patch soon. For the time being, feel free to try again with `rev: a6d5a14f6881d763859cd4f765ca31e79d6a006c`
